# Generated by Django 3.2.4 on 2021-07-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='position_level',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
