# Generated by Django 3.2.4 on 2021-07-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0003_posting_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='skills',
            field=models.CharField(max_length=256),
        ),
    ]
