# Generated by Django 3.2.4 on 2021-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0004_alter_posting_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='responsibilities',
            field=models.TextField(),
        ),
    ]
