# Generated by Django 3.2.4 on 2021-07-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0006_auto_20210707_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='level',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='posting',
            name='other',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
