# Generated by Django 3.2.4 on 2022-08-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0007_auto_20210707_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='place',
            new_name='location',
        ),
    ]
