# Generated by Django 3.2.3 on 2021-06-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='wordlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.wordlist'),
        ),
    ]
