# Generated by Django 3.2.4 on 2021-07-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='list_card_uppercase',
            new_name='card_title_uppercase',
        ),
    ]
