# Generated by Django 3.1.4 on 2021-03-05 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_worddict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.RemoveField(
            model_name='word',
            name='wordlist',
        ),
        migrations.AddField(
            model_name='word',
            name='users',
            field=models.ManyToManyField(related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='wordlists',
            field=models.ManyToManyField(blank=True, related_name='words', to='vocabulary.WordList'),
        ),
    ]
