# Generated by Django 3.2.4 on 2021-07-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_word_wordlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
