# Generated by Django 3.2.4 on 2021-07-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_rename_list_card_uppercase_settings_card_title_uppercase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
