# Generated by Django 3.1.4 on 2021-03-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_auto_20210304_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='worddict',
            name='meaning',
            field=models.TextField(blank=True),
        ),
    ]
