# Generated by Django 3.2.4 on 2022-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=16)),
                ('origin', models.CharField(max_length=32)),
                ('origin_code', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=32)),
                ('destination_code', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('duration', models.TimeField()),
                ('aircraft_type', models.CharField(max_length=8)),
                ('cruising_altitude', models.CharField(max_length=5)),
                ('distance', models.IntegerField()),
                ('route', models.TextField()),
            ],
        ),
    ]
